### ISSUE TITLE
Error with HTTPAuth by using Custom verify

### ISSUE THREAD

**Issue by Chaostheorie** [miguelgrinberg/Flask-HTTPAuth#89]
I have a broken auth that hangs, itdelf up in the verify_password phase
For the creation I have followed the Blog Entry/ guide [Here](https://blog.miguelgrinberg.com/post/restful-authentication-with-flask) for creating the basic sheme with HTTPAuth
To reproduce (testeed on ubuntu 19.04/PYthon 3.7.3):
git clone https://github.com/Chaostheorie/Penta-Tournament 
cd https://github.com/Chaostheorie/Penta-Tournament
(virtualenv -p python3 venv)
pip3 install -r requeriemtns.txt
python3 main.py

Now start a post (JSON) request to localhost:5000/api/user/sign-in and create your user 
Then try to get your token at localhost:5000/api/user/token

The authentication will crash at the point with the traceback:
AttributeError: 'Flask' object has no attribute 'lower'
127.0.0.1 - - [31/Oct/2019 22:58:31] "POST /api/user/token HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/<user>/Penta-Tournament/Backend/venv/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/<user>/Penta-Tournament/Backend/venv/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/home/<user>/Penta-Tournament/Backend/venv/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/<user>/Penta-Tournament/Backend/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/<user>Penta-Tournament/Backend/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/<user>/Penta-Tournament/Backend/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/<user>/Penta-Tournament/Backend/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/<user>/Penta-Tournament/Backend/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/<user>/Penta-Tournament/Backend/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/<user>/Penta-Tournament/Backend/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/<user>/Penta-Tournament/Backend/venv/lib/python3.7/site-packages/flask_httpauth.py", line 91, in decorated
    auth = self.get_auth()
  File "/home/<user>/Penta-Tournament/Backend/venv/lib/python3.7/site-packages/flask_httpauth.py", line 75, in get_auth
    if auth is not None and auth.type.lower() != self.scheme.lower():
AttributeError: 'Flask' object has no attribute 'lower'

I don't really get how the Flask Object ended up there and how I can pass the right thing for this function
Thanks in advance

**Comment by miguelgrinberg** [comment]
You are initializing the HTTPBasicAuth object incorrectly. You are passing the Flask app instance to it, while this extension does not require it, and instead uses different arguments. Remove the `app` argument and you should be fine.

**Comment by Chaostheorie** [comment]
Thanks for the quick help. The fix worked perfectly.
